"""Keyword dictionaries used to map playlist titles to narrative categories."""

from __future__ import annotations

CATEGORY_KEYWORDS = {
    "sad": {
        "sad",
        "cry",
        "crying",
        "heartbreak",
        "breakup",
        "depressed",
        "lonely",
        "pain",
        "tears",
        "in my feels",
        "feels",
    },
    "hype": {
        "hype",
        "lit",
        "turn up",
        "party",
        "banger",
        "rage",
        "pregame",
        "club",
        "dance",
    },
    "study": {
        "study",
        "focus",
        "deep work",
        "homework",
        "coding",
        "concentration",
        "productivity",
        "lofi",
        "instrumental",
    },
    "workout": {
        "gym",
        "workout",
        "running",
        "run",
        "lifting",
        "cardio",
        "training",
        "exercise",
        "spin",
    },
    "sleep": {
        "sleep",
        "bedtime",
        "night",
        "calm",
        "meditation",
        "ambient",
        "rain",
        "rest",
        "relax",
    },
    "road_trip": {
        "road trip",
        "driving",
        "car",
        "highway",
        "travel",
        "trip",
        "adventure",
    },
    "romance": {
        "love",
        "romance",
        "wedding",
        "date",
        "valentine",
        "crush",
        "kiss",
    },
}

STOP_WORDS = {
    "a",
    "an",
    "and",
    "are",
    "at",
    "be",
    "for",
    "from",
    "in",
    "is",
    "it",
    "me",
    "my",
    "of",
    "on",
    "or",
    "the",
    "to",
    "with",
    "playlist",
    "music",
    "songs",
    "mix",
    "best",
    "new",
}
